### PR TITLE
Use vercel adapter to fix ssr

### PR DESCRIPTION
**Pull request by chvanam**
Salut! 

Navigating to [https://locutionis.vercel.app/glossary](https://locutionis.vercel.app/glossary) (and all other routes) gives a 404 not found error.
I believe it is a misconfiguration of the `adapter-static` when hosting only static files on Vercel.
This PR switches to the `adapter-vercel` to easily fix this bug. (I came across it when trying to add a page bookmark)

Please tell me if this fix is an applicable solution for your setup !

### CODE REVIEW

**Comment by pBouillon** [comment]
Bonjour !

Thanks a lot for spotting this bug, I didn't catch it when migrating from GitHub Pages to Vercel
I could sure use this kind of improvement !

However, it seems that there is a lot of dependencies that were added into the project (`@iarna/toml`, `@sveltejs/adapter-cloudflare`, etc.), could you only remove the previous `adapter-static` and add the new `adapter-vercel` ?
Thanks a lot !

**Comment by chvanam** [comment]
My bad, from reading the [adapter-vercel](https://github.com/sveltejs/kit/tree/master/packages/adapter-vercel#adapter-vercel) documentation I thought it was included as a default SvelteKit dependency in `adapter-auto`.
It turns out you can use it standalone.
This also removes a lot of previous build dependencies I see.

**Note that you would have to specify a new Vercel build output directory to `.vercel_build_output`**, I don't think Vercel recognises it automatically.

**Comment by pBouillon** [comment]
Thank you for removing the unnecessary dependencies !

Indeed, the `docs/` folder is served by default, I will change the configuration once this PR has been merged

Looking at the Vercel logs, it seems that the build step is failing with the following errors:

```
[18:57:13.500] Cloning github.com/pBouillon/locutionis (Branch: main, Commit: 86529a6)
[18:57:13.903] Cloning completed: 402.515ms
[18:57:14.273] Installing build runtime...
[18:57:16.167] Build runtime installed: 1.893s
[18:57:16.835] Looking up build cache...
[18:57:18.655] Build cache downloaded [30.37 MB]: 1463.815ms
[18:57:18.786] Installing dependencies...
[18:57:18.786] Detected `package-lock.json` generated by npm 7...
[18:57:19.648] 
[18:57:19.648] > locutionis@0.0.1 prepare
[18:57:19.648] > svelte-kit sync
[18:57:19.648] 
[18:57:19.786] 
[18:57:19.786] removed 11 packages in 781ms
[18:57:19.786] 
[18:57:19.786] 42 packages are looking for funding
[18:57:19.786]   run `npm fund` for details
[18:57:19.990] Detected `package-lock.json` generated by npm 7...
[18:57:19.990] Running "npm run build"
[18:57:20.272] 
[18:57:20.272] > locutionis@0.0.1 build
[18:57:20.272] > svelte-kit build
[18:57:20.272] 
[18:57:20.588] [36mvite v2.8.6 [32mbuilding for production...[36m[39m
[18:57:20.680] transforming...
[18:57:21.876] [32m✓[39m 18 modules transformed.
[18:57:21.876] [31m[vite:esbuild] The package "esbuild-linux-64" could not be found, and is needed by esbuild.
[18:57:21.876] 
[18:57:21.877] If you are installing esbuild with npm, make sure that you don't specify the
[18:57:21.877] "--no-optional" flag. The "optionalDependencies" package.json feature is used
[18:57:21.877] by esbuild to install the correct binary executable for your current platform.[39m
[18:57:21.877] file: [36m/vercel/path0/src/lib/functions/api.ts[39m
[18:57:21.878] > The package "esbuild-linux-64" could not be found, and is needed by esbuild.
[18:57:21.878] 
[18:57:21.878] If you are installing esbuild with npm, make sure that you don't specify the
[18:57:21.878] "--no-optional" flag. The "optionalDependencies" package.json feature is used
[18:57:21.878] by esbuild to install the correct binary executable for your current platform.
[18:57:21.879] 
[18:57:21.879] If you are installing esbuild with npm, make sure that you don't specify the
[18:57:21.879] "--no-optional" flag. The "optionalDependencies" package.json feature is used
[18:57:21.879] by esbuild to install the correct binary executable for your current platform.
[18:57:21.880]     at generateBinPath (/vercel/path0/node_modules/esbuild/lib/main.js:1818:15)
[18:57:21.880]     at esbuildCommandAndArgs (/vercel/path0/node_modules/esbuild/lib/main.js:1874:31)
[18:57:21.880]     at ensureServiceIsRunning (/vercel/path0/node_modules/esbuild/lib/main.js:2036:25)
[18:57:21.881]     at Object.transform (/vercel/path0/node_modules/esbuild/lib/main.js:1931:37)
[18:57:21.881]     at transformWithEsbuild (/vercel/path0/node_modules/vite/dist/node/chunks/dep-9c153816.js:22415:38)
[18:57:21.881]     at async Object.transform (/vercel/path0/node_modules/vite/dist/node/chunks/dep-9c153816.js:22468:32)
[18:57:21.881]     at async transform (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:21995:16)
[18:57:21.882]     at async ModuleLoader.addModuleSource (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:22221:30)
[18:57:21.882] [!] Error: unfinished hook action(s) on exit:
[18:57:21.882] (vite-plugin-svelte) transform "/vercel/path0/src/routes/index.svelte"
[18:57:21.883] (vite-plugin-svelte) transform "/vercel/path0/src/routes/glossary/[name].svelte"
[18:57:21.883] (vite:css) transform "/vercel/path0/src/app.css"
[18:57:21.883] (vite:css) transform "/vercel/path0/node_modules/bootstrap-icons/font/bootstrap-icons.css"
[18:57:21.883] (vite:esbuild) transform "/vercel/path0/src/lib/functions/theme.ts"
[18:57:21.883] 
[18:57:21.901] Error: Command "npm run build" exited with 1
```

Any lead on that ?

**Comment by chvanam** [comment]
Must have mixed up the dependencies some way. Will close in favour of your pull request #30.
Congrats on your mention on the [Svelte blog](https://svelte.dev/blog/whats-new-in-svelte-may-2022#community-showcase) by the way !

**Comment by pBouillon** [comment]
Will do !

Thank you for your time, I really appreciate it 😄 

I didn't even knew I was on it, what a nice surprise, thanks for sharing !

**Pull request closed without merging**
